### ISSUE TITLE
Replace method with constructor

### ISSUE THREAD

**Issue by Splines** [compose-generator/ccom#14]
Why is this not a constructor?

https://github.com/compose-generator/ccom/blob/78b923bdfe4eb370a237f34a4c2b3b59cdf43c1e/compiler/cpp/src/lexer/lexer.cpp#L272-L287

**Comment by marcauberer** [comment]
Historic remnant as always 😅
Will fix it soon ...

**Comment by marcauberer** [comment]
@Splines if we would want to do this with a construcor, we should have a class first ;) So, do we still want to do this?

**Comment by Splines** [comment]
> @Splines if we would want to do this with a construcor, we should have a class first ;) So, do we still want to do this?

Of course. Especially with regards to #15 .
