### ISSUE TITLE
Use `startsWith` instead of `substr`

### ISSUE THREAD

**Issue by Splines** [compose-generator/ccom#17]
Is there a `startsWith()` method in C++?

https://github.com/compose-generator/ccom/blob/78b923bdfe4eb370a237f34a4c2b3b59cdf43c1e/compiler/cpp/src/lexer/lexer.cpp#L252-L255

**Comment by marcauberer** [comment]
@Splines no, but there is [an alternative](https://stackoverflow.com/a/8095132/6296634).
