### ISSUE TITLE
Forgot to advance in while loop

### ISSUE THREAD

**Issue by Splines** [compose-generator/ccom#23]
We need an `reader.advance()` here. Otherwise this is going to end up in an infinite loop.

https://github.com/compose-generator/ccom/blob/78b923bdfe4eb370a237f34a4c2b3b59cdf43c1e/compiler/cpp/src/lexer/lexer.cpp#L218-L219

**Comment by marcauberer** [comment]
Nope. The loop head contains an advance call. Closing this ...
