### ISSUE TITLE
Better just use substr?

### ISSUE THREAD

**Issue by keksklauer4** [compose-generator/ccom#32]
https://github.com/compose-generator/ccom/blob/7044ed217de38905339ab7cc125a3aac75c87636/compiler/java/src/main/java/com/c/reader/Reader.java#L132

**Comment by Splines** [comment]
@keksklauer4 Could you elaborate a bit more on your intended usage of `substr` since I don't really get what you mean... I don't try to return a substring here but the next chars - which is of type `LimitedQueue<Character>` as a `String` - as String. I don't see where I could use `substr` here.

**Comment by Splines** [comment]
@keksklauer4 ?

**Comment by marcauberer** [comment]
@keksklauer4 when the bug is not relevant anymore, please let us know. Otherwise we will close this issue

**Comment by keksklauer4** [comment]
We talked about it. No need to change anything, I was just confused about you using a Queue of chars.
