### ISSUE TITLE
Move token types from lexer to token class

### ISSUE THREAD

**Issue by Splines** [compose-generator/ccom#8]
@marcauberer I think it'd be better to move the token types to the token header file.

https://github.com/compose-generator/ccom/blob/4d6794800c6ad2a825702215e425de9b311af5af/compiler/cpp/src/lexer/lexer.h#L16-L51

**Comment by marcauberer** [comment]
The next pr will be a dedicated one, for code optimization stuff:
- Avoid dynamic cast
- Move token types to Token class
- Change attributes to lower-case
