### ISSUE TITLE
Don't increase position on EOF

### ISSUE THREAD

**Issue by Splines** [compose-generator/ccom#9]
We shouldn't increase the position after having reached EOF since this will screw up the `Math.min(...)` calculation otherwise.

https://github.com/compose-generator/ccom/blob/4d6794800c6ad2a825702215e425de9b311af5af/compiler/cpp/src/lexer/lexer.cpp#L26-L35

https://github.com/compose-generator/ccom/blob/4d6794800c6ad2a825702215e425de9b311af5af/compiler/cpp/src/lexer/lexer.cpp#L45-L48

In Java, I will implement it like this:

```java
    /**
     * Consumes current char and advances to next character.
     */
    private void advance() {
        // Check for EOF
        if (position == file.length - 1) {
            next = 0; // 0 stands for EOF
            return;
        }

        // Increase head position (if not EOF)
        position++;

        // Read next char
        next = file[position];
        lineCol++;
    }
```

**Comment by marcauberer** [comment]
Oh. That's indeed something we should fix ...
